version: '3.9'
services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    container_name: boilerplate-postgre
    env_file: .env
    environment:
      POSTGRES_MULTIPLE_DATABASES: ${BOILERPLATE_DB_DATABASE},${BOILERPLATE_DB_DATABASE}_test
      POSTGRES_USER: ${BOILERPLATE_DB_USERNAME}
      POSTGRES_PASSWORD: ${BOILERPLATE_DB_PASSWORD}
      POSTGRES_SCHEMA: ${BOILERPLATE_DB_SCHEMA}
    ports:
      - '${BOILERPLATE_DB_PORT}:5432'
    volumes:
      - ./postgres-scripts/:/docker-entrypoint-initdb.d/
      - ./boilerplate-db:/var/lib/postgresql/data
    networks:
      - boilerplatenetwork

  api:
    restart: unless-stopped
    env_file: .env
    container_name: boilerplate-api
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
    command: npm run start:dev
    environment:
      BOILERPLATE_DB_HOST: postgres
      BOILERPLATE_DB_PORT: 5432
      DATABASE_URL: postgresql://${BOILERPLATE_DB_USERNAME}:${BOILERPLATE_DB_PASSWORD}@postgres:5432/${BOILERPLATE_DB_DATABASE}?schema=${BOILERPLATE_DB_SCHEMA}
    tty: true
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - postgres
    ports:
      - '${PORT}:3000'
    networks:
      - boilerplatenetwork
volumes:
  boilerplate-db:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules

networks:
  boilerplatenetwork:
    driver: bridge
